### PR TITLE
fix: Fallback chunk is now loaded in production mode

### LINKED ISSUE #662: Fallback chunk not loaded in production mode
**To reproduce**

Clone Spring [starter](https://github.com/vaadin/skeleton-starter-flow-spring), then replace MainView ctor with:
```java
try {
    Class c = Class.forName("com.vaadin.flow.component.checkbox.Checkbox");
    add((Component) c.newInstance());
} catch (Exception e) {
    e.printStackTrace();
}
```
Creating a `CheckBox` using reflection will evade the bytecode scanning and force use of the fallback chunk in production mode (and in development mode if `devmode.optimizeBundle` is true). Start app in production mode (profile `production`). 

**Observed behavior**: the added checkbox has no shadow root, meaning that it's frontend module is not loaded.

**Expected behavior**: the component frontend code should have been loaded via the fallback chunk.

**Versions**: Vaadin 14.3, Vaadin 17

See https://vaadin.com/forum/thread/18445598/production-mode-doesn-t-work-while-everthing-works-well-in-development-mode for details.

### PR DESCRIPTION
**Pull request by joheriks**
Non-string init parameter (`DeploymentConfigurationFactory.FALLBACK_CHUNK`)  in `Properties`object was lost in the Spring properties mapping.

Fixes #662.

### CODE REVIEW

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java [hunk 1]
```diff
@@ -90,4 +93,20 @@ public void pushURL_rootMappingAndCustomURLWithVaadinServletPrefix_isNotAddition
...
+    public void fallbackChunk_givenInInitParameter_passedOnToDeploymentConfiguration()
+            throws ServletException {
+        FallbackChunk fallbackChunk = new FallbackChunk(Collections.emptyList(),
+                Collections.emptyList());
+        final Properties properties = new Properties();
+        properties.put(DeploymentConfigurationFactory.FALLBACK_CHUNK,
+                fallbackChunk);
+        VaadinService service = SpringInstantiatorTest.getService(context,
+                properties, true);
+        Assert.assertEquals(fallbackChunk,
```
Comment (denis-anisimov) [inline vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java:108]: `assertSame` may be is better

**Review by denis-anisimov — CHANGES_REQUESTED** [review]

**Review by denis-anisimov — APPROVED** [review]

File: vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java (hunk 1 above)
Comment (joheriks) [reply vaadin-spring/src/test/java/com/vaadin/flow/spring/service/SpringServletTest.java]: Done.
