### PR TITLE
Hardcode adding DragSource to found classes in DevModeServletContextListener

### LINKED ISSUE #519: JsModules from interfaces are not added to frontend bundle
- Using Spring starter with 14.0 and updating it to 14.1.
- With a simple view and components implementing DragSource and DropTarget
- Compile and run in development mode
The resulting application throws client-side exceptions for `cannot read property 'updateDragSource' of undefined` and `cannot read property 'updateDropTarget' of undefined`.
It seems that dndConnector.js is not included

### PR DESCRIPTION
**Pull request by mehdi-vaadin**
Fix #519

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/spring/520)

### CODE REVIEW

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java [hunk 1]
```diff
@@ -324,6 +326,30 @@ public void contextInitialized(ServletContextEvent event) {
...
+            // manually.
+            getClassByName("com.vaadin.flow.component.dnd.DragSource")
+                    .ifPresent(types::add);
+            getClassByName("com.vaadin.flow.component.dnd.DropTarget")
+                    .ifPresent(types::add);
+
+            return types;
+        }
+
+        private Optional<Class> getClassByName(String name) {
```
Comment (knoobie) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java]: Parameter name is not used

Comment (mehdi-vaadin) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java]: @knoobie thanks.
