### PR TITLE
fix: replace 'blocklist' and 'whitelist' with 'blocked' and 'allowed'

### LINKED ISSUE #645: Alternative names for `blacklisted-packages` and `whitelisted-packages`
Property `blacklisted-packages` is currently used to specifically exclude packages from scanning for annotations etc., while `whitelisted-packages` is used to exclusively include packages in scanning. These names do not convey the semantics of the properties very well, and there are indications that these terms are being perceived as increasingly dated by the developer community. 

If done, documentation should be updated and support previous names as well for backwards compatibility. Other property naming related issues that may be relevant to consider at the same time are #634 and #637.

### PR DESCRIPTION
**Pull request by jouni**
Fixes #645

Mark the existing methods as deprecated and introduce methods with new names.

Fall back to the old configuration properties if the new ones aren't used.

### CODE REVIEW

**Comment by jouni** [comment]
I admit I did the changes almost “blindfolded”. I didn't run any tests or otherwise verify that it works. I hope someone can tell me how to do that, or do it for me 😄

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 1]
```diff
@@ -112,39 +112,83 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
 
     /**
-     * Get a list of packages that are blacklisted for class scanning.
+     * Get a list of packages that are blocked for class scanning.
      *
-     * @return package blacklist
+     * @return blocked packages
+     * @deprecated use getBlockedPackages()
      */
+    @Deprecated
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:120]: It would be good to add the `forRemoval=true` attribute

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 2]
```diff
@@ -112,39 +112,83 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
 
     /**
-     * Get a list of packages that are white-listed for class scanning.
+     * Set a list of packages to ignore for class scanning.
      *
-     * @return package white-list
+     * @param blockedPackages list of packages to ignore
+     * @deprecated use setBlockedPackages()
+     */
+    @Deprecated
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:140]: It would be good to add the `forRemoval=true` attribute

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 3]
```diff
@@ -112,39 +112,83 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
+    }
+
+    /**
+     * Set list of packages to be scanned. If <code>allowedPackages</code>
+     * is set then <code>blockedPackages</code> is ignored.
+     *
+     * @param allowedPackages list of packages to be scanned
+     * @deprecated use setAllowedPackages()
+     */
+    @Deprecated
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:181]: It would be good to add the `forRemoval=true` attribute

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 4]
```diff
@@ -112,39 +112,83 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
+        this.blockedPackages = new ArrayList<>(blockedPackages);
+    }
+
+    /**
+     * Get a list of packages that are allowed for class scanning.
+     *
+     * @return allowed packages
+     * @deprecated use getAllowedPackages()
      */
     public List<String> getWhitelistedPackages() {
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:161]: Needs `@Deprecated` annotation

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java [hunk 5]
```diff
@@ -520,12 +522,19 @@ public void contextDestroyed(ServletContextEvent sce) {
...
     public VaadinServletContextInitializer(ApplicationContext context) {
         appContext = context;
         String neverScanProperty = appContext.getEnvironment()
-                .getProperty("vaadin.blacklisted-packages");
+                .getProperty("vaadin.blocked-packages");
+        if (neverScanProperty == null) {
+            neverScanProperty = appContext.getEnvironment()
+                    .getProperty("vaadin.blacklisted-packages");
+            if (neverScanProperty != null) {
+                getLogger().warn("vaadin.blacklisted-packages is deprecatd. Use vaadin.blocked-packages instead.");
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java]: How about putting a little more pressure on the developer?

```suggestion
                getLogger().warn("vaadin.blacklisted-packages is deprecatd and may not be supported anymore in the future. Use vaadin.blocked-packages instead.");
```

**Review by mcollovati — CHANGES_REQUESTED** [review]
A bunch of comments.
Validation is failing, I'll try it locally

**Comment by mcollovati** [comment]
The same changes should be applied also on Flow repository.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java (hunk 2 above)
Comment (jouni) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:140]: Done.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java (hunk 1 above)
Comment (jouni) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:120]: Done.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java (hunk 3 above)
Comment (jouni) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:181]: Done.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java (hunk 4 above)
Comment (jouni) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java:161]: Added.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java (hunk 5 above)
Comment (jouni) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java]: Sure, thanks. Fixed one typo at the same time.

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 6]
```diff
@@ -112,39 +112,84 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
 
     /**
-     * Get a list of packages that are white-listed for class scanning.
+     * Set a list of packages to ignore for class scanning.
      *
-     * @return package white-list
+     * @param blockedPackages list of packages to ignore
+     * @deprecated use setBlockedPackages()
      */
+    @Deprecated(forRemoval = true)
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java]: My bad, `forRemoval` is not available in Java 8
```suggestion
    @Deprecated
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 7]
```diff
@@ -112,39 +112,84 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
 
     /**
-     * Get a list of packages that are blacklisted for class scanning.
+     * Get a list of packages that are blocked for class scanning.
      *
-     * @return package blacklist
+     * @return blocked packages
+     * @deprecated use getBlockedPackages()
      */
+    @Deprecated(forRemoval = true)
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java]: My bad, `forRemoval` is not available in Java 8
```suggestion
    @Deprecated
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 8]
```diff
@@ -112,39 +112,84 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
+        this.blockedPackages = new ArrayList<>(blockedPackages);
+    }
+
+    /**
+     * Get a list of packages that are allowed for class scanning.
+     *
+     * @return allowed packages
+     * @deprecated use getAllowedPackages()
+     */
+    @Deprecated(forRemoval = true)
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java]: My bad, `forRemoval` is not available in Java 8
```suggestion
    @Deprecated
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java [hunk 9]
```diff
@@ -112,39 +112,84 @@ public void setPnpmEnabled(boolean pnpmEnabled) {
...
+    }
+
+    /**
+     * Set list of packages to be scanned. If <code>allowedPackages</code>
+     * is set then <code>blockedPackages</code> is ignored.
+     *
+     * @param allowedPackages list of packages to be scanned
+     * @deprecated use setAllowedPackages()
+     */
+    @Deprecated(forRemoval = true)
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinConfigurationProperties.java]: My bad, `forRemoval` is not available in Java 8
```suggestion
    @Deprecated
```

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java [hunk 10]
```diff
@@ -535,7 +544,14 @@ public VaadinServletContextInitializer(ApplicationContext context) {
         }
 
         String onlyScanProperty = appContext.getEnvironment()
-                .getProperty("vaadin.whitelisted-packages");
+                .getProperty("vaadin.allowed-packages");
+        if (onlyScanProperty == null) {
+            onlyScanProperty = appContext.getEnvironment()
+                    .getProperty("vaadin.whitelisted-packages");
+            if (onlyScanProperty != null) {
+                getLogger().warn("vaadin.whitelisted-packages is deprecatd. Use vaadin.allowed-packages instead.");
```
Comment (mcollovati) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/VaadinServletContextInitializer.java]: I would use a message similar to the one used for `blacklisted-packages
```suggestion
                getLogger().warn("vaadin.whitelisted-packages is deprecatd and may not be supported in the future. Use vaadin.allowed-packages instead.");
```

**Review by mcollovati — CHANGES_REQUESTED** [review]

**Comment by Artur-** [comment]
Shouldn't this be done in https://github.com/vaadin/flow/tree/main/vaadin-spring ? This repository is for old Flow versions

**Comment by mcollovati** [comment]
> Shouldn't this be done in https://github.com/vaadin/flow/tree/main/vaadin-spring ? This repository is for old Flow versions

I'll create a PR in the flow repo

**Review by mcollovati — APPROVED** [review]
The PR looks good, but tests are still failing, although they pass locally.
I'm looking into it, but in the meanwhile I'll create a specular PR on the Flow repository

**Comment by mcollovati** [comment]
https://github.com/vaadin/flow/pull/18405

**Comment by mcollovati** [comment]
Tests failed because of issues with pnpm cache; browser console reported messages like

```
http://ip-address:8888/parent-template 0:0 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegist…-module" has already been used with this registry
http://ip-address:8888/parent-template 0:0 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegist…-module" has already been used with this registry
```

Cleaning pnpm cache before executing the validation fixed the job

**Comment by mcollovati** [comment]
@mshabarov LGTM, I don't know if you also want to take a look at it

**Review by mshabarov — APPROVED** [review]
Looks good to me.

"Blocked-packages" and "allowed-packages" names are inline with what we previously discussed in Slack.

**Comment by mshabarov** [comment]
We have to pick this into 19.1 branch as well.

**Comment by jouni** [comment]
Thanks for helping out with the finalization tasks!
