### PR TITLE
fix: Spring Boot 2.6 compatibility

### LINKED ISSUE #941: Does not work with Spring Boot 2.6
Seems like Spring Boot 2.6 removed `ResourceProperties` which is used in some hacky code in https://github.com/vaadin/spring/blob/dee6efa77a5cb4455ebcc244b4a25778b2eeefa4/vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java#L136

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #941

### CODE REVIEW

**Comment by ZheSun88** [comment]
do we need to update https://github.com/vaadin/spring/blob/master/pom.xml#L47 to spring-boot 2.6.0?

**Comment by Artur-** [comment]
This PR should be compatible with Spring Boot 2.4+. Maybe we should still update the version at the same time

**Comment by Artur-** [comment]
This fix could go into V22, we probably shouldn't go to Spring Boot 2.6 for that at this point

**Comment by Artur-** [comment]
Let's do the version update in #940

**Comment by knoobie** [comment]
The FQN defined in isSpringBootConfigured is probably faulty as well

**Comment by lmorocz** [comment]
And there is an extra `org.springframework.boot.autoconfigure.web.ResourceProperties.class` in the `isSpringBootConfigured` method as well.

**Comment by Artur-** [comment]
Simplified

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java [hunk 1]
```diff
@@ -22,6 +22,8 @@
 import java.util.Optional;
 import java.util.stream.Collectors;
 
+import org.springframework.beans.factory.NoSuchBeanDefinitionException;
+import org.springframework.boot.autoconfigure.web.WebProperties.Resources;
```
Comment (knoobie) [inline vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java:26]: Is this class to be expected to work with plain spring or just spring boot?

**Review by platosha — DISMISSED** [review]

**Comment by haijian-vaadin** [comment]
could you @Artur- help to fix the sonar issue, let's get this merged soon

File: vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java (hunk 1 above)
Comment (Artur-) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java:26]: It is supposed to work with Spring. Seems like there are no proper tests for plain Spring projects in this repository

Comment (Artur-) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java]: Let's keep the untested code then and hope that it might work with plain Spring..

Comment (knoobie) [reply vaadin-spring/src/main/java/com/vaadin/flow/spring/SpringVaadinServletService.java]: I would like to have a more spring boot oriented implementation as well.. but I've seen multiple PRs in this repo in the past where explicitly a more complex route was taken to reduce the coupling with spring boot.. that's why I wanted to mention it

**Comment by mstahv** [comment]
I wouldn't care about Sonar issues at all, but Spring Boot 2.6.0 support for 22 would be cool ;-)

**Comment by knoobie** [comment]
^ for 14.6 as well 😀

**Comment by mstahv** [comment]
For 14 series as well yeah 👍

**Comment by Artur-** [comment]
Seems to work now, just waiting for a review

**Review by caalador — APPROVED** [review]

**Comment by joheriks** [comment]
> Seems like this is already in the 19.0 branch
There was no `19.0` branch at that point, created it after this commit.
